### ISSUE TITLE
Example incomplete, signalling server?

### ISSUE THREAD

**Issue by ZoolWay** [webrtc-uwp/PeerCC#1]
Unfortunately the example lacks documentation. What kind of (signalling) server does it want to connect to?

**Comment by robin-raymond** [comment]
@ZoolWay The repos were just reorganized to get WebRTC for UWP building much easier. I'm in the process of adding in more in this area, including the server. Right now it's just the basic WebRTC "peer connection client" server without modification from webrtc.org. In coming weeks it will be published as part of the WebRTC SDK. At least as soon as I'm able to complete the upgrade process.

**Comment by NinoStella** [comment]
Any update about server adding?

**Comment by abrantie11z** [comment]
Anybody having an idea what signaling server to connect to?

**Comment by HoloJackStones** [comment]
You can use the PeerConnectionServer.exe 

https://github.com/webrtc-uwp/PeerCC-Sample/tree/master/Server

**Comment by SergioOpenPeer** [comment]
If you are interested just in PeerCC sample, then you should get this sample from another repo https://github.com/webrtc-uwp/PeerCC-Sample In this version, PeerCC depends on nuget package and server binary is provided too.

If you are interested in webrtc or server debugging or modifying you should clone this repo  https://github.com/webrtc-uwp/webrtc-uwp-sdk, where (https://github.com/webrtc-uwp/PeerCC) is included like a submodule.

You can build server following these steps:
1. Clone webrtc-uwp-sdk: git clone --recursive https://github.com/webrtc-uwp/webrtc-uwp-sdk.git
2. cd webrtc-uwp-sdk
3. bin\prepare.bat
4. From VS2015, open webrtc\windows\solutions\WebRtc.sln
5. Build server project in Samples/PeerCC/Server
6. PeerCC server executable you can find in webrtc\xplatform\webrtc\build_win32\(Debug\Release)\peerconnection_server.exe

From WebRtc.sln solution you can run also PeerCC or ChatterBox sample applications, and do WebRtc lib debugging.

**Comment by abrantie11z** [comment]
But this server is for test I guess on a local machine  .a peer in another machine can't see this server right?

**Comment by SergioOpenPeer** [comment]
You can run server on what ever machine you want, you can make it even to be a public. Just get its IP address and use it for connecting PeerCC clients.
To make a proper audio/video call you have to have at least two machines. On one, you can run server and client, and on another just run the client which will connect to server, and you will be able to make a call between two peers.

**Comment by abrantie11z** [comment]
How do I get its ip address and how do I make it public? Because when I run the server, all I see is server running on port 8888. .

**Comment by SergioOpenPeer** [comment]
http://www.wikihow.com/Find-out-Your-IP-Address

**Comment by abrantie11z** [comment]
So in this case. I will type the public ip address of computer on the other machine?

**Comment by SergioOpenPeer** [comment]
If server and clients are all in local network you will use server local ip address. If you make your server to be public and visible outside your local network then, you will type server public ip address.

**Comment by robin-raymond** [comment]
If you have to use a public IP then you'll need to open up your firewall to the signalling server between machines.

**Comment by abrantie11z** [comment]
If I understand both of clearly,  I will need to open a firewall on the machine the server is running on so is visible to the outside world?  Can I do that in code and how pls?

**Comment by robin-raymond** [comment]
@abrantie11z doing in code wouldn't be worth it for testing purposes. It's better just to open the firewall manually for now.

**Comment by abrantie11z** [comment]
Alright will do that.Thank you very much! Mr Robin and Mr.Sergio!  I guess this won't be needed if u make the live server .

**Comment by abrantie11z** [comment]
Hi. .am done with the datachannel sample..was fun.  Am now on peer  cc sample. .I realized it uses webrtc,  hence sdp. . I also realised there is a compiler directive to use ortclib. .I tried installing ortc nugent package so I use ortc  but it didn't work
