### ISSUE TITLE
No signaling server

### ISSUE THREAD

**Issue by abrantie11z** [webrtc-uwp/PeerCC#4]
Is there any open test signaling server we can connect to aside building ur own signaling server on local host that can't be detected by others?

**Comment by robin-raymond** [comment]
Hi @abrantie11z - not at the moment. We are looking into setting up a public server.

@SergioOpenPeer Do you have instructions where to obtain the server?

**Comment by SergioOpenPeer** [comment]
@abrantie11z Please, read last comment at this link https://github.com/webrtc-uwp/PeerCC/issues/1
