### ISSUE TITLE
Where is the source code for signaling server?

### ISSUE THREAD

**Issue by TonyRedGraive** [webrtc-uwp/PeerCC#5]

**Comment by veikkoeeva** [comment]
I would be interested to know also. Moreover, could there be some parts in .NET (OK with C++ too if there's a codebase that doesn't rely on print-debugging :)) that could be re-used to create a signaling server? I have very limited exposure to stun/turn, so starting one from scratch would be a no-go unless helping with PRs here and there.

**Comment by TonyRedGraive** [comment]
I ended up with writing code from scratch using Node.js.

PS. Sorry for my English.

**Comment by veikkoeeva** [comment]
@TonyRedGraive There are some Node.js signalling servers, I think. Care to share yours? I'd prefer .NET (or C++) as I know my way around with those better. :P

**Comment by TonyRedGraive** [comment]
Sorry. I cannot share my code right now. 
I studied from this link: [](https://www.html5rocks.com/en/tutorials/webrtc/infrastructure/).
Hope this will help you.

**Comment by jamescadd** [comment]
@veikkoeeva Here's one option, though it is Node: https://github.com/anastasiia-zolochevska/signaling-server

Note there are a few issues in using that server directly with the samples in this repo, but if you're just rewriting signaling from scratch it may be a good guide.

**Comment by jamescadd** [comment]
Also the source for the signaling server used in the PeerConnection client repo is available here: https://github.com/webrtc-uwp/webrtc/tree/master/examples/peerconnection/server
